
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ProjectPart1A( // top-level module

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
reg [31:0] clockCount;


//=======================================================
//  Structural coding
//=======================================================
ClockDivider (CLOCK_50, clockCount);

reg [9:0] leds;
assign LEDR = leds;

always@(clockCount == 0)
leds = 10'b1111111111;


endmodule


// 7/29/15 working
module ClockDivider (input myClock, output reg[31:0] count);

parameter clockdivisor = 100_000_000;

always@(posedge myClock)
	if(count==0)
		count <= clockdivisor;
	else 
		count <= count-1;
endmodule
