//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ProjectPart1A( // top-level module

 //////////// CLOCK //////////
 input               CLOCK_50,
 input               CLOCK2_50,
 input               CLOCK3_50,
 input               CLOCK4_50,

 //////////// SEG7 //////////
 output       [6:0]  HEX0,
 output       [6:0]  HEX1,
 output       [6:0]  HEX2,
 output       [6:0]  HEX3,
 output       [6:0]  HEX4,
 output       [6:0]  HEX5,

 //////////// KEY //////////
 input        [3:0]  KEY,

 //////////// LED //////////
 output       [9:0]  LEDR,

 //////////// SW //////////
 input        [9:0]  SW,

 //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
 inout       [35:0]  GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
reg [31:0] clockCount;


//=======================================================
//  Structural coding
//=======================================================

wire[31:0]clk;
parameter whichClock = 25;
clock_divider myclockdivider(CLOCK_50, clk);
assign LEDR[0]=clk[whichClock];

endmodule


// 8/3/15 working
module clock_divider (clock, divided_clocks);
 input clock;
 output[31:0]divided_clocks;
 reg [31:0] divided_clocks;
 initial 
  divided_clocks = 0;
 always@(posedge clock)
  divided_clocks = divided_clocks + 1;
endmodule

module Scan(input CLOCK_50, 
            input[7:0] keypad, 
            output reg[3:0] rawkey, 
				output reg rawValid);
	
	wire[3:0] rows;
	wire[3:0] cols; 
	reg[31:0] counter;
	reg[1:0] colsNum;
	reg[3:0] decodedcols;
	
   parameter clockDivisor = 500;
	wire Allrows = rows[0]& rows[1]& rows[2]& rows[3];

	assign cols = keypad[3:0];
	assign rows = keypad[7:4];

	always @(posedge CLOCK_50)
		begin 
			if (counter==0)
		begin
			counter <= clockDivisor;
			if (Allrows==1)
			colsNum<=colsNum+1;
		end
    else 
		counter <= counter -1;
    end

	 always@( colsNum)
		case (colsNum)
		0: decodedcols = 4'b0111;
		1: decodedcols = 4'b1011;
		2: decodedcols = 4'b1101;
		3: decodedcols = 4'b1110;
		endcase
//
//		always@(*)
//			if (Allrows ==1)
//			begin
//				rawkey =0;
//				rawValid = 0;
//			end
//			else
//			begin
//				case (rows)
//				4'0xxx:
//				begin
//					rawkey ={2'b00, colsNum}
//				if 
 
endmodule